### ISSUE TITLE
H872 Loose Fast Charging With Melina Reborn From r1 to r4.

### ISSUE THREAD

**Issue by javashin** [zefie/lge_g6_melina_kernel#3]
Hi This Is Been Happening All The Time No Fast Charge I Tried Carbon LineageOS HavocOS Same Problem The Stock Kernels In The Roms Can Fast Charge Rapidly Charging With Melina Reborn I Got Cahrging Slowly All The Time When I Connect It To The PC Or By The Wall With A Fast Charger Brick.
No Idea Whats Going On I Need DriveDroid And This Kernel Provides It. The Cd Emulation.  And I Used GeekBench 5 To Get The Performance From Stock 8.0.0 Oreo On This T-Mobile Lg g6 And Drops From   5XX points to 3XX With Vulkan Compute Test So There Is A Huge Performance Drop Also I Cannot Charge While The Phone Is OFF Seems Like A General Problem. Thanks In Advance Your Stock Kernel Melina Works Nice If Can I Get A Update Not Soon Just If u Like to update the non-reborn that can be great . im not thinking on use a custom rom anytime for now until all those bugs i discovered get squashed . Thanks For Your Kernels And Great Job.

**Comment by zefie** [comment]
> Hi This Is Been Happening All The Time No Fast Charge I Tried Carbon LineageOS HavocOS Same Problem The Stock Kernels In The Roms Can Fast Charge Rapidly Charging With Melina Reborn I Got Cahrging Slowly All The Time When I Connect It To The PC Or By The Wall With A Fast Charger Brick.

I think Fast Charging only works when the screen is off, but I am not sure. I have seen it say "Charging Rapidly", but that was not the 9v fast charge, that was just 2A 5v. I also lost my original LG charger, and only have my Samsung Adaptive Charger, and I do not know if they are compatible. So it is hard for me to test. However, try flipping the USB-C cable. I don't know why, but sometimes I get "Charging Rapidly" only if I flip my cable.

> No Idea Whats Going On I Need DriveDroid And This Kernel Provides It. The Cd Emulation.

DriveDroid should work, though I haven't tested it on 10, and it is an old app. Please note that it won't work for DVD ISOs (while this limitation is in the Kernel, even current Linux OS kernels have the same limitation, they never enabled DVD ISO for USB Gadget, the last time I checked.)

> And I Used GeekBench 5 To Get The Performance From Stock 8.0.0 Oreo On This T-Mobile Lg g6 And Drops From 5XX points to 3XX With Vulkan Compute Test So There Is A Huge Performance Drop

This does not sound right, but to verify please try again with rel_r3 (and not rel_r4) to confirm if I missed an optimization flag in rel_r4 or not (if so, it will be fixed in future rel_r5)

> Also I Cannot Charge While The Phone Is OFF Seems Like A General Problem. 

This is also fixed in future rel_r5 :)

>Thanks In Advance Your Stock Kernel Melina Works Nice If Can I Get A Update Not Soon Just If u Like to update the non-reborn that can be great . 

Old Melina won't be updated but should still work on the old stock roms just fine.

> im not thinking on use a custom rom anytime for now until all those bugs i discovered get squashed .  Thanks For Your Kernels And Great Job.

Sadly since none of this is supported its bound to always have a bug or two, but hopefully, most will be squashed soon! For example, we still don't have IMS (VoLTE, VoWifi, etc)

**Comment by javashin** [comment]
Thanks for the Reply.

**Comment by zefie** [comment]
Here is a stock friendly release: https://github.com/zefie/lge_g6_melina_kernel/releases/tag/rel_p1
